### PR TITLE
Fix for cargo configurator protection bypass problem

### LINKED ISSUE #117: [BUG] Cargo Configurator can use on protected area
## Description (REQUIRED)

Cargo Configurator can use on protected area.
Example.: Griefprevention protection, PlotSquared protected plots.

## Steps to reproduce the Issue (REQUIRED)

1. Use Cargo Configurator on the protected area to copy and apply cargo configuration.
2. Copy and apply works perfectly on protected area.

## Expected behavior (REQUIRED)

Cargo Configurator cannot use on protected area if I don't have access to.

## Environment (REQUIRED)

[17:54:53 INFO]: This Server uses the following setup of Slimefun:
[17:54:53 INFO]: Yatopia v1_16_R3
[17:54:53 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[17:54:53 INFO]: Slimefun vDEV - 757 (git 77f4373b)
[17:54:53 INFO]: Metrics build: #17
[17:54:53 INFO]:
[17:54:53 INFO]: Installed Addons: (1)
[17:54:53 INFO]:  LiteXpansion vDEV - 98 (git f79eab2f)

### PR DESCRIPTION
**Pull request by TryHardDo**
## Short Description

I just added few lines to the CargoConfigurator class which checks the player building priveleges every time when iteract with the CargoConfigurator tool. I also added a small fix for a problem when the tool is disabled in the slimefun items config the player still can use it.

## Additions/Changes/Removals

Added CS-CoreLib checker to make sure the tools is enabled on the server
Added ProtectionManager from the SlimeFun library
Added CS-CoreLib localization when the user doesn't have permission to modify the cargo settings.
I added **slimefun.cargo.bypass** permission as a cargo configurator protection bypass permission. So if somebody has this perm he can bypass the protection.

## Related Issues

Resolves #117

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

File: src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java [hunk 1]
```diff
@@ -47,6 +51,11 @@ public ItemUseHandler getItemHandler() {
         return e -> e.setUseBlock(Event.Result.DENY);
     }
 
+    public boolean canUseCargoConfigurator(@Nonnull Player p, @Nonnull Block clicked) {
+        return SlimefunPlugin.getProtectionManager().hasPermission(p, clicked, ProtectableAction.ACCESS_INVENTORIES);
+    }
+
+
```
Comment (J3fftw1) [inline src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java]: weird empty space but lgtm

**Review by J3fftw1 — APPROVED** [review]

File: src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java [hunk 2]
```diff
@@ -47,6 +51,11 @@ public ItemUseHandler getItemHandler() {
         return e -> e.setUseBlock(Event.Result.DENY);
     }
 
+    public boolean canUseCargoConfigurator(@Nonnull Player p, @Nonnull Block clicked) {
+        return SlimefunPlugin.getProtectionManager().hasPermission(p, clicked, ProtectableAction.ACCESS_INVENTORIES);
+    }
```
Comment (WalshyDev) [inline src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java]: This is used once, don't see the point. Should be private anyway

File: src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java (hunk 1 above)
Comment (WalshyDev) [inline src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java]: :wut:

File: src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java [hunk 3]
```diff
@@ -94,6 +103,16 @@ public void onCargoConfiguratorItemClick(PlayerInteractEvent e) {
             return;
         }
 
+        if (SlimefunItem.getByItem(Items.CARGO_CONFIGURATOR).isDisabled()) {
```
Comment (WalshyDev) [inline src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java]: We already do an item lookup before with `isItem`. Condense these into one (especially since it shouldn't run anything if disabled) save an item lookup

File: src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java [hunk 4]
```diff
@@ -94,6 +103,16 @@ public void onCargoConfiguratorItemClick(PlayerInteractEvent e) {
...
+            return;
+        }
+
+        Player p = e.getPlayer();
```
Comment (WalshyDev) [inline src/main/java/dev/j3fftw/litexpansion/items/CargoConfigurator.java]: final also call it `player`

**Review by WalshyDev — CHANGES_REQUESTED** [review]

**Comment by J3fftw1** [comment]
Thanks for the pr <3
