### PR TITLE
Fixes #74

### LINKED ISSUE #74: Multiple Food Synthesizers in a player's inventory all feed them at once.
## :round_pushpin: Description (REQUIRED)
Should a player desire to spend more time away from base without needing to eat or recharge, one may choose to bring multiple food synthesizers with them. However, they will find that whether the food synthesizers are stacked or not, all food synthesizers will lose 3 joules whenever the player gets hungry.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
Have more than one food synthesizer in your inventory. They must have some charge. Whether they are stacked or not doesn't matter.

## :bulb: Expected behavior (REQUIRED)
It may be expected that food synthesizers drain in the offhand slot and hotbar first, then the top row of the inventory, then the middle row, etc., with food synthesizers to the left depleting before those further right. If two or more food synthesizers are stacked, they become unstacked before one discharges, leaving the ones that were removed from the stack to either find a new slot in the inventory or be dropped on the ground.

## :scroll: Server Log

No relevant errors thrown by server.

## :open_file_folder: /error-reports/ Folder

No relevant error reports saved by server.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper v1.16.R2
 - Minecraft Version: v1.16.3
 - Slimefun Version: vDEV-680
 - CS-CoreLib Version: vDEV-90
 - LiteExpansion Version: vDEV-72

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Short Description

This pull request fixes Issue #74 by adding a break statement after a Food Synthesizer has been located in the inventory, this will also benefit the performance as it reduces unnecessary iterations through the inventory.

## Additions/Changes/Removals

* Refactored GlowEnchant to use a HashSet
* Added some Nonnull and Nullable annotations
* Removed the registration of the LiteXpansion category (Categories are automatically registered once they have at least one item)

## Related Issues

Resolves #74

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

File: src/main/java/dev/j3fftw/litexpansion/LiteXpansion.java [hunk 1]
```diff
@@ -55,10 +55,10 @@ public void onEnable() {
         } catch (IllegalAccessException | NoSuchFieldException ignored) {
             getLogger().warning("Failed to register enchantment. Seems the 'acceptingNew' field changed monkaS");
         }
-        Enchantment.registerEnchantment(new GlowEnchant(Constants.GLOW_ENCHANT));
 
-        // Category
-        Items.LITEXPANSION.register();
```
Comment (J3fftw1) [inline src/main/java/dev/j3fftw/litexpansion/LiteXpansion.java:61]: reason you removed this?

**Review by J3fftw1 — CHANGES_REQUESTED** [review]

File: src/main/java/dev/j3fftw/litexpansion/LiteXpansion.java (hunk 1 above)
Comment (TheBusyBiscuit) [reply src/main/java/dev/j3fftw/litexpansion/LiteXpansion.java:61]: I literally explained it in the PR body...

Comment (J3fftw1) [reply src/main/java/dev/j3fftw/litexpansion/LiteXpansion.java:61]: lol didnt see that line

**Comment by J3fftw1** [comment]
Thanks for adding this btw ❤️

**Comment by TheBusyBiscuit** [comment]
You're welcome :D
I wanted to fix at least one or two bugs in LX this month anyway, but but I decided to also include that Glow Enchant refactoring I've been calling out for weeks XD

**Comment by TheBusyBiscuit** [comment]
And I only now realized I worked of off `master` :NotLikeThis:
Oh well

**Comment by J3fftw1** [comment]
let me merge it for you
